spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/futrue?useUnicode=true&characterEncodeing=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: lx@lx19870613
#mybatis:
#  mapper-locations: classpath:mapper/SqlMapper.xml

